

python train_la_dtc_ce_loss_32label_ema_update.py
python train_la_dtc_ce_loss_64label_ema_update.py

python train_la_dtc_mes_loss_32label_ema_update.py
python train_la_dtc_mes_loss_64label_ema_update.py
